//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: persistent_msgs.proto

package pvtdatastorage

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ExpiryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map map[string]*Collections `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExpiryData) Reset() {
	*x = ExpiryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persistent_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpiryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpiryData) ProtoMessage() {}

func (x *ExpiryData) ProtoReflect() protoreflect.Message {
	mi := &file_persistent_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpiryData.ProtoReflect.Descriptor instead.
func (*ExpiryData) Descriptor() ([]byte, []int) {
	return file_persistent_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *ExpiryData) GetMap() map[string]*Collections {
	if x != nil {
		return x.Map
	}
	return nil
}

type Collections struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// for pvt data, there would be an
	// entry in TxNums
	Map map[string]*TxNums `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// for any number of missing pvt data of a collection,
	// there would be an entry in the map
	MissingDataMap map[string]bool `protobuf:"bytes,2,rep,name=missingDataMap,proto3" json:"missingDataMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *Collections) Reset() {
	*x = Collections{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persistent_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Collections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collections) ProtoMessage() {}

func (x *Collections) ProtoReflect() protoreflect.Message {
	mi := &file_persistent_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collections.ProtoReflect.Descriptor instead.
func (*Collections) Descriptor() ([]byte, []int) {
	return file_persistent_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *Collections) GetMap() map[string]*TxNums {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *Collections) GetMissingDataMap() map[string]bool {
	if x != nil {
		return x.MissingDataMap
	}
	return nil
}

type TxNums struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []uint64 `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *TxNums) Reset() {
	*x = TxNums{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persistent_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxNums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxNums) ProtoMessage() {}

func (x *TxNums) ProtoReflect() protoreflect.Message {
	mi := &file_persistent_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxNums.ProtoReflect.Descriptor instead.
func (*TxNums) Descriptor() ([]byte, []int) {
	return file_persistent_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *TxNums) GetList() []uint64 {
	if x != nil {
		return x.List
	}
	return nil
}

type CollElgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsCollMap map[string]*CollNames `protobuf:"bytes,1,rep,name=nsCollMap,proto3" json:"nsCollMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CollElgInfo) Reset() {
	*x = CollElgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persistent_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollElgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollElgInfo) ProtoMessage() {}

func (x *CollElgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_persistent_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollElgInfo.ProtoReflect.Descriptor instead.
func (*CollElgInfo) Descriptor() ([]byte, []int) {
	return file_persistent_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *CollElgInfo) GetNsCollMap() map[string]*CollNames {
	if x != nil {
		return x.NsCollMap
	}
	return nil
}

type CollNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *CollNames) Reset() {
	*x = CollNames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persistent_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollNames) ProtoMessage() {}

func (x *CollNames) ProtoReflect() protoreflect.Message {
	mi := &file_persistent_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollNames.ProtoReflect.Descriptor instead.
func (*CollNames) Descriptor() ([]byte, []int) {
	return file_persistent_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *CollNames) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_persistent_msgs_proto protoreflect.FileDescriptor

var file_persistent_msgs_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x76, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x76, 0x74, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x1a, 0x53, 0x0a,
	0x08, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x76, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xb1, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x36, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x70, 0x76, 0x74, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x57, 0x0a, 0x0e, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x76, 0x74, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x4d, 0x61, 0x70, 0x1a, 0x4e, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x76, 0x74, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x54, 0x78, 0x4e, 0x75, 0x6d, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x41, 0x0a, 0x13, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1c, 0x0a, 0x06, 0x54, 0x78, 0x4e, 0x75, 0x6d, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x45, 0x6c, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x48, 0x0a, 0x09, 0x6e, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x4d, 0x61,
	0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x76, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x45, 0x6c, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4e, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x09, 0x6e, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x1a, 0x57,
	0x0a, 0x0e, 0x4e, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x76, 0x74, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x25, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x3a,
	0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70,
	0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x76, 0x74, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_persistent_msgs_proto_rawDescOnce sync.Once
	file_persistent_msgs_proto_rawDescData = file_persistent_msgs_proto_rawDesc
)

func file_persistent_msgs_proto_rawDescGZIP() []byte {
	file_persistent_msgs_proto_rawDescOnce.Do(func() {
		file_persistent_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_persistent_msgs_proto_rawDescData)
	})
	return file_persistent_msgs_proto_rawDescData
}

var file_persistent_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_persistent_msgs_proto_goTypes = []interface{}{
	(*ExpiryData)(nil),  // 0: pvtdatastorage.ExpiryData
	(*Collections)(nil), // 1: pvtdatastorage.Collections
	(*TxNums)(nil),      // 2: pvtdatastorage.TxNums
	(*CollElgInfo)(nil), // 3: pvtdatastorage.CollElgInfo
	(*CollNames)(nil),   // 4: pvtdatastorage.CollNames
	nil,                 // 5: pvtdatastorage.ExpiryData.MapEntry
	nil,                 // 6: pvtdatastorage.Collections.MapEntry
	nil,                 // 7: pvtdatastorage.Collections.MissingDataMapEntry
	nil,                 // 8: pvtdatastorage.CollElgInfo.NsCollMapEntry
}
var file_persistent_msgs_proto_depIdxs = []int32{
	5, // 0: pvtdatastorage.ExpiryData.map:type_name -> pvtdatastorage.ExpiryData.MapEntry
	6, // 1: pvtdatastorage.Collections.map:type_name -> pvtdatastorage.Collections.MapEntry
	7, // 2: pvtdatastorage.Collections.missingDataMap:type_name -> pvtdatastorage.Collections.MissingDataMapEntry
	8, // 3: pvtdatastorage.CollElgInfo.nsCollMap:type_name -> pvtdatastorage.CollElgInfo.NsCollMapEntry
	1, // 4: pvtdatastorage.ExpiryData.MapEntry.value:type_name -> pvtdatastorage.Collections
	2, // 5: pvtdatastorage.Collections.MapEntry.value:type_name -> pvtdatastorage.TxNums
	4, // 6: pvtdatastorage.CollElgInfo.NsCollMapEntry.value:type_name -> pvtdatastorage.CollNames
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_persistent_msgs_proto_init() }
func file_persistent_msgs_proto_init() {
	if File_persistent_msgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_persistent_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpiryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persistent_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Collections); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persistent_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxNums); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persistent_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollElgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persistent_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollNames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_persistent_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_persistent_msgs_proto_goTypes,
		DependencyIndexes: file_persistent_msgs_proto_depIdxs,
		MessageInfos:      file_persistent_msgs_proto_msgTypes,
	}.Build()
	File_persistent_msgs_proto = out.File
	file_persistent_msgs_proto_rawDesc = nil
	file_persistent_msgs_proto_goTypes = nil
	file_persistent_msgs_proto_depIdxs = nil
}
